name: Build and deploy
on:
  push:
    branches: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: docker://jekyll/jekyll
      with:
        entrypoint: bash
        args:  -c "/usr/local/bin/bundle install && /usr/local/bin/bundle exec jekyll build"
    - name: Deploy
      run: |
        sudo chown -R $(whoami):$(whoami) .
        MESSAGE="$(git log --oneline --format=%B -n1 | head -n1)"
        cp -r _site /tmp
        git checkout master
        rm -rf *
        mv /tmp/_site/* .
        git add --all --force
        git commit --allow-empty-message --author "" --message "$MESSAGE"
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        git push --force origin master
